version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    build: ./db
    volumes:
      - "./db/data:/data/db"
    ports:
      - "27017:27017"
